[tool.black]
line-length = 100
target-version = ['py37']

include = '\.pyi?$'

exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | build
    | out
    | htmlcov
    | node_modules
    | pytest-config
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''