#!/bin/sh -e

rootdir=$(git rev-parse --show-toplevel)
(
    cd $rootdir
    rm -rf dist .cache *.egg-info _build *.tests
    find ./ -name '*.pyc' -delete
    tox
    python setup.py check -r
    python setup.py --long-description | rst2html5 > /dev/null
)
