resources:
  repositories:
  - repository: tox
    type: github
    endpoint: github
    name: tox-dev/azure-pipelines-template
    ref: refs/tags/0.2

trigger:
- master
- release

jobs:
- template: run-tox-env.yml@tox
  parameters:
    name: CI
    tox_version: 'tox'
    jobs:
      docs: null
      py37:
        image: [linux, windows, macOs]
    coverage:
      with_toxenv: 'coverage'
      for_envs: [py37]

- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/release') }}:
  - template: publish-pypi.yml@tox
    parameters:
      dependsOn: [CI]
      external_feed: 'daquiri'
      pypi_remote: ''